### ISSUE TITLE
Ranking systeem voor moeilijkheidsgraad

### ISSUE THREAD

**Issue by Vinestou** [DutchDomotics/dd-sitesrc#7]
Uitwerken en implementeren van een ranking systeem om de moeilijkheidsgraad weer te geven aan lezers van to do's, tutorials posts.

Dit kan d.m.v.:
* Punten
* Sterren
* Schaal
* Levels (easy/medium/hard)

Als extra gebruik maken van tags om sortering/groepering te maken.

**Comment by TheGabeMan** [comment]
Starten met drie niveau's op basis van tags? Als je met levels of sterren begint en je blijkt later nog een extra level te willen hebben, dan moet je misschien de oude herzien. 

Met tags zou je behalve level ook de uitgebreidheid van de uitleg kunnen weergeven. Een artikel heeft dan twee tags:
Starter = Simpele automations of andere zaken bouwen.
Discoverer = Als je de basis zaken in HA hebt zitten, maar nu de smaak echt te pakken hebt.
Been-there-done-that = voor de Expert die alles al geautomatiseerd maar net nog deze unicorn mist.

Take-me-by-the-hand = Uitgebreide uitleg, echt stap voor stap zodat niks mis kan gaan incl wat meer uitleg over wat je nu eigenlijk aan het doen bent. Iets wat ik probeer met mijn roborock tutorial.
General-direction = Wel nog een handleiding of stappen nodig, maar er wordt al wat basis kennis verwacht.
Hints-only = "Oh maar dan moet je die entity even boolean maken"

**Comment by Vinestou** [comment]
Lijkt me een goed idee! Het hoeft ook geen klaslokaal te worden met cijfers of mario met sterren. Ik ben voor maar wel max 4 niveau's. KISS
